name: Lint

on:
  push:
    branches: ['main']
  pull_request:
  workflow_dispatch: # Allows running the workflow manually from the Actions tab

permissions:
  contents: read
  actions: write

env:
  FORCE_COLOR: 1

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
          cache: 'pip'
      - uses: pre-commit/action@v3.0.1
